# Generated by Django 5.2.5 on 2026-08-07 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0008_publicacion_categoria_publicacion_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ASIGNADO', 'Repartidor asignado'), ('LLEGO_RECOGIDA', 'Repartidor ha llegado al restaurante'), ('EN_CAMINO_ENTREGA', 'Repartidor salio con tu pedido'), ('LLEGO_ENTREGA', 'Repartidor ha llegado a tu direccion'), ('FINALIZADO', 'Pedido finalizado')], default='ASIGNADO', max_length=20)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('llego_recogida_en', models.DateTimeField(blank=True, null=True)),
                ('salio_en', models.DateTimeField(blank=True, null=True)),
                ('llego_entrega_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='market.pedido')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepartidorPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repartidor_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
