# Generated by Django 5.2.17 on 2026-08-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='distancia_validacion_metros',
            field=models.FloatField(default=0.0),
        ),
    ]
