# Generated by Django 5.2.5 on 2026-08-19 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_asignacion_distancia_validacion_metros'),
        ('market', '0012_pedido_calificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoRechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechazos', to='market.pedido')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_rechazados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pedido', 'repartidor')},
            },
        ),
    ]
