from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class RepartidorRepository(Protocol):
    def get_or_create_perfil(self, usuario: Any) -> Any: ...

    def set_activo(self, perfil: Any, activo: bool) -> None: ...

    def update_ubicacion(self, perfil: Any, *, latitud: float, longitud: float) -> None: ...


@runtime_checkable
class AsignacionRepository(Protocol):
    def get_active_for_repartidor(self, usuario: Any) -> Any | None: ...

    def get_by_pedido_id(self, pedido_id: int) -> Any | None: ...

    def create(self, *, pedido: Any, repartidor: Any) -> Any: ...

    def mark_llego_recogida(self, asignacion: Any) -> None: ...

    def mark_salio(self, asignacion: Any) -> None: ...

    def mark_llego_entrega(self, asignacion: Any) -> None: ...

    def mark_finalizado(self, asignacion: Any) -> None: ...


@runtime_checkable
class PedidoDeliveryRepository(Protocol):
    def list_pending_near(self, *, latitud: float, longitud: float, radius_km: float) -> list[Any]: ...

    def get_by_id(self, pedido_id: int) -> Any | None: ...

    def mark_entregado(self, pedido: Any) -> None: ...
