# Generated by Django 5.2.17 on 2026-08-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_publicacion_categoria_publicacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='propina',
            field=models.FloatField(default=0.0),
        ),
    ]
