# Generated by Django 5.2.17 on 2026-08-14 03:42

import market.domain.image_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_pedido_propina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='publicaciones/', validators=[market.domain.image_validation.validate_publicacion_imagen]),
        ),
    ]
