# Generated by Django 5.2.17 on 2026-08-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(db_index=True, default='ACTIVA', max_length=20),
        ),
    ]
