# Generated by Django 5.2.5 on 2026-08-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_pedido_estado_alter_publicacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='calificado',
            field=models.BooleanField(default=False),
        ),
    ]
