# Generated by Django 5.2.5 on 2026-08-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_pedido_calificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen_thumb',
            field=models.FileField(blank=True, null=True, upload_to='publicaciones/thumbs/'),
        ),
    ]
