# Generated by Django 5.2.5 on 2026-08-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_repartidor',
            field=models.BooleanField(default=False),
        ),
    ]
