# Generated by Django 5.2.17 on 2026-08-08 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_es_repartidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion_texto', models.CharField(max_length=255)),
                ('detalles', models.CharField(blank=True, default='', max_length=255)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_guardadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-es_predeterminada', '-creado_en'],
            },
        ),
    ]
