# Generated by Django 5.2.5 on 2026-08-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_direccionguardada'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_calificaciones',
            field=models.IntegerField(default=0),
        ),
    ]
